*The DLT algorithm computes a homography by using point correspondences to form a
linear system whose solution gives the projective transformation between two images.
It uses SVD to find the homography matrix that best satisfies the mapping in
homogeneous coordinates.*

In [1]:
import numpy as np
import numpy.linalg as la

O3 = np.array([0,0,0])

def dveJed(Ah, A1h):
    jed1 = np.concatenate((O3, -A1h[2] * Ah, A1h[1] * Ah))
    jed2 = np.concatenate((A1h[2] * Ah, O3, -A1h[0] * Ah))

    return np.array([jed1, jed2])


def DLT(pts, pts1):
    A = []

    for i in range(len(pts)):
        dve = dveJed(pts[i], pts1[i])
        A.append(dve[0])
        A.append(dve[1])

    A = np.array(A)
    
    U, S, Vh = la.svd(A)
    matP = Vh[8].reshape(3, 3)

    return matP / matP[2, 2]


In [2]:
M = np.array([
    [1,  2,  3],
    [3,  2,  1],
    [1, -2,  1],
    [1,  1,  1],
    [0, -2,  3],
    [1,  0, -1]
], dtype=float)

Mp = np.array([
    [29.3, -3.2, 10.9],   # M1p
    [35.1,  1.6, 18.3],   # M2p
    [ 7.2, -6.5,  2.5],   # M3p
    [16.1, -0.4,  7.4],   # M4p
    [ 9.3, -11.2, -0.2],  # M5p
    [ 2.9,  2.4,  3.7]    # M6p
], dtype=float)

In [3]:
P = DLT(M, Mp)
print(P)

[[ 8.25366196  2.94205585  5.16486657]
 [-0.04878715  2.1330488  -2.48601309]
 [ 4.82254299  1.60389175  1.        ]]


In [4]:
Ah = np.array([1, 2, -3])
Bh = np.array([1, 0, -1])
Ch = np.array([1, 2, 0])
Dh = np.array([3, -2, 1])
A1h = np.array([-6, -7, 17])
B1h = np.array([-4, 1, 5])
C1h = np.array([9, 11, 26])
D1h = np.array([0, 23, 9])

pts = [Ah, Bh, Ch, Dh]
pts1 = [A1h, B1h, C1h, D1h]
3*DLT(pts, pts1)

array([[1., 4., 5.],
       [7., 2., 6.],
       [8., 9., 3.]])